# Pull Ubuntu base image
FROM ubuntu:18.04 
## The MAINTAINER instruction sets the author field of the generated images.
MAINTAINER ulsordonez@unicauca.edu.co
# Configure environment path
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
#### Install all necessary packages

RUN apt-get -y update && apt install -y python3-dev wget git curl
RUN echo "Python3, curl, git installed correctly"
#### Configuring conda environment: https://docs.conda.io/en/latest/miniconda.html#linux-installers 
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh \
    && mkdir root/.conda \
    && sh Miniconda3-py37_4.12.0-Linux-x86_64.sh -b \
    && rm -f Miniconda3-py37_4.12.0-Linux-x86_64.sh
RUN echo "Conda environment 'ml' installed correctly"
RUN conda create -y -n ml python==3.7
RUN /bin/bash  -c "source activate ml"

#---------------------START GCLOUD CONFIG--------------------------------------------
# Downloading gcloud package
#RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz

# Installing the package
#RUN mkdir -p /usr/local/gcloud \
#  && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
#  && /usr/local/gcloud/google-cloud-sdk/install.sh

# Adding the package path to local
#ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin


RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin
 #--------------------- END GCLOUD CONFIG--------------------------------------------
# Run the code:
COPY . Dengue/

#RUN /bin/bash  -c "cd Dengue && pip install -r requirements.txt && python coordinate_extraction.py"
#RUN cd Dengue \
#    && "source activate ml" \
#    && pip install -r requirements.txt \
#    && python coordinate_extraction.py

#---------------------START SentinelHub CONFIG--------------------------------------------
#RUN cd Dengue \
#    && source activate ml \
#    && git clone https://github.com/sentinel-hub/sentinelhub-py.git \
#    && cd sentinelhub-py && pip install -r requirements.txt && python setup.py build && python setup.py install
#    && python satellite.extractor.py

#RUN /bin/bash -c "cd sentinelhub-py && pip install -r requirements.txt && python setup.py build && python setup.py install"
#RUN cd Dengue \
#    && source activate ml \
#    python satellite.extractor.py

#---------------------START SentinelHub CONFIG--------------------------------------------
